### ISSUE TITLE
Switching between tabs causes flicker on iPad

### ISSUE THREAD

**Issue by unarist** [MasterDalK/kktCSS#38]
Some user [reported](https://kirakiratter.com/@itayakaede/226974) this issue from kktCSS v7.6, and I've confirmed this still exists on my iPad Air.

https://cloud.githubusercontent.com/assets/705555/25518846/63b02cca-2c30-11e7-8e12-5b6c341e59b1.gif

I found the problem will solved if I remove `width: calc(...)` style.

```css
@media screen and (min-width: 768px) {
  .tabs-bar {
    padding-left: 75px;
  }

  .tabs-bar:first-child {
    width: calc(100% - 95px) !important; /* HERE */
    margin-left: auto;
  }

  .tabs-bar__link {
    padding: 16px 8px;
  }
}
```

I don't know why `width: calc(...)` was [introduced](https://github.com/MasterDalK/kktCSS/commit/1df5b125#diff-8f960ca2444a592030335bd0d1162754R695), but can we remove this line?
