### ISSUE TITLE
Should we keep fallbacks on gradient background?

### ISSUE THREAD

**Issue by unarist** [MasterDalK/kktCSS#47]
```css
.status,
.notification,
.onboarding-modal__pager::before,
.confirmation-modal,
.boost-modal {
  /* Old browsers */
  background: rgb(252, 252, 225);
  /* FF3.6-15 */
  background: -moz-linear-gradient(top, rgba(252, 252, 225, 1) 0%, rgba(252, 252, 225, 1) 65%, rgba(252, 252, 225, 1) 65%, rgba(249, 240, 174, 1) 100%);
  /* Chrome10-25,Safari5.1-6 */
  background: -webkit-linear-gradient(top, rgba(252, 252, 225, 1) 0%, rgba(252, 252, 225, 1) 65%, rgba(252, 252, 225, 1) 65%, rgba(249, 240, 174, 1) 100%);
  /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
  background: linear-gradient(to bottom, rgba(252, 252, 225, 1) 0%, rgba(252, 252, 225, 1) 65%, rgba(252, 252, 225, 1) 65%, rgba(249, 240, 174, 1) 100%);
  /* IE6-9 */
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#fcfce1', endColorstr='#f9f0ae', GradientType=0);
  border-radius: 8px;
  border: solid 2px #e1c152;
  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.4);
}
```

IIRC, Mastodon doesn't seem to support Internet Explorer (incl. IE11!) and other legacy browsers. So can we get rid those polyfills?

```css
.status,
.notification,
.onboarding-modal__pager::before,
.confirmation-modal,
.boost-modal {
  background: linear-gradient(to bottom, rgba(252, 252, 225, 1) 0%, rgba(252, 252, 225, 1) 65%, rgba(252, 252, 225, 1) 65%, rgba(249, 240, 174, 1) 100%);
  border-radius: 8px;
  border: solid 2px #e1c152;
  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.4);
}
```
