### ISSUE TITLE
[RFC] More styling on composer form (i.e. Katsu! form)

### ISSUE THREAD

**Issue by unarist** [MasterDalK/kktCSS#48]
It's just an idea for now...

![image](https://cloud.githubusercontent.com/assets/705555/25561205/46a1f4de-2da1-11e7-9a04-7a75eeb3546d.png) ![image](https://cloud.githubusercontent.com/assets/705555/25561238/8e0366e0-2da2-11e7-8fe4-db6697048b1c.png)
![image](https://cloud.githubusercontent.com/assets/705555/25561109/37f20962-2d9f-11e7-9b29-ea0523e31af4.png) ![image](https://cloud.githubusercontent.com/assets/705555/25561301/20c47856-2da4-11e7-9e21-c641ebfabe6e.png)

```css
.navigation-bar {
  background: hsla(325, 58%, 48%, 0.6);
}

.icon-button.inverted.active,
.text-icon-button.active {
  color: #96b34c; /* green */
  color: #e56cac; /* lighter pink */
  color: #c33488; /* darker pink */
}

.privacy-dropdown__option:hover,
.privacy-dropdown__option.active {
  background: hsla(77, 40%, 50%, 1); /* green */
  background: hsla(330, 80%, 70%, 1); /* lighter pink */
  background: hsla(325, 58%, 48%, 1); /* darker pink */
}
.privacy-dropdown__option.active:hover {
  background: hsla(77, 40%, 55%, 1); /* green */
  background: hsla(330, 80%, 75%, 1);  /* lighter pink */
  background: hsla(325, 58%, 53%, 1); /* darker pink */
}
```

**Comment by MasterDalK** [comment]
I really like the light pink, but probably good to use the green one since that's what all the other settings are coloured. I also tried colouring the text and icons without hover, what do you think?

![capture](https://cloud.githubusercontent.com/assets/24326990/25561449/1eb7e346-2d3a-11e7-9956-1c743253d71e.PNG)

**Comment by MasterDalK** [comment]
This has the strong text colour match the highlight colour

![image](https://cloud.githubusercontent.com/assets/24326990/25561468/6e41b616-2d3b-11e7-8577-79c253582348.png)

**Comment by bit-map** [comment]
I like the green as the highlight color but it loses a little something when everything is green. I would say keep the non-highlighted options either black or brown?

**Comment by unarist** [comment]
I think that non-highlighted options should be more darken.

hsla(77, **35%**, 20%, 1) / hsla(77, 25%, 45%, 1)

![image](https://cloud.githubusercontent.com/assets/705555/25564669/4e4f19ee-2df3-11e7-9c69-18ddd2c42116.png)

hsla(77, **25%**, 20%, 1) / hsla(77, 25%, 45%, 1)

![image](https://cloud.githubusercontent.com/assets/705555/25564789/8ad2314c-2df5-11e7-8ebb-40a0c132adc9.png)

The latter one seems almost the same as original one, but the former one is also good I think.

**Comment by bit-map** [comment]
Darkening the green works a lot better for me than having icons/header/description all the same color. Between the two options, I'd have to say I prefer the second one because it pops out. I don't think being close to the original (but different in hue) is a bad thing.

**Comment by MasterDalK** [comment]
I like the last set as well. I'll throw it in the new version.

**Comment by unarist** [comment]
Also, how about lighten background? (see my first examples)

```css
.navigation-bar {
  hsla(325, 58%, 48%, 0.6);
}
.drawer__inner {
  background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" height="28" width="20"><rect height="28" width="20" y="0" x="0" fill="#e46bac"/><path d="m0 14 10-14 10 14-10 14z" fill="#df57a4"/></svg>');
}
```
