### ISSUE TITLE
[RFC] More styling on composer form (closed as duplicate of #48)

### ISSUE THREAD

**Issue by unarist** [MasterDalK/kktCSS#49]
It's just an idea for now...

![image](https://cloud.githubusercontent.com/assets/705555/25561205/46a1f4de-2da1-11e7-9a04-7a75eeb3546d.png)

![image](https://cloud.githubusercontent.com/assets/705555/25561109/37f20962-2d9f-11e7-9b29-ea0523e31af4.png)

![image](https://cloud.githubusercontent.com/assets/705555/25561238/8e0366e0-2da2-11e7-8fe4-db6697048b1c.png)

```css
.navigation-bar {
  background: hsla(325, 58%, 48%, 0.6);
}

.icon-button.inverted.active,
.text-icon-button.active {
  color: #96b34c; /* green */
  color: #e56cac; /* lighter pink */
  color: #c33488; /* darker pink */
}

.privacy-dropdown__option:hover,
.privacy-dropdown__option.active {
  background: hsla(77, 40%, 50%, 1); /* green */
  background: hsla(330, 80%, 70%, 1); /* lighter pink */
  background: hsla(325, 58%, 48%, 1); /* darker pink */
}
.privacy-dropdown__option.active:hover {
  background: hsla(77, 40%, 55%, 1); /* green */
  background: hsla(330, 80%, 75%, 1);  /* lighter pink */
  background: hsla(325, 58%, 53%, 1); /* darker pink */
}
```
